credentials:
  usernames:
    daynite:
      email: it@wearetheone.com
      name: Day & Nite User
      password: $2b$12$iqILbAIRYYNEnZ9wh.0ch.gY1abbuWaEhYHihsOhI3BZ14NIkDtHm
cookie:
  expiry_days: 7
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails: